name: NoCure
main: prevent.curing.NoCure
version: 1.1
api-version: 1.21
author: VazarinX
description: Prevents players from curing zombie villagers
website: https://github.com/VazarinX/NoCure-Zombie-Villagers
softdepend:
  - DiscordSRV
